config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    resources :posts, only: [:create, :update, :index, :destroy]
  end
  root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
end

app/controllers/api/posts_controller.rb
class Api::PostsController < ApplicationController

  def index
    render json: Post.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/_header.html.erb
<div ng-controller="menuController as menu">

  <nav class="navbar navbar-default navbar-fixed-top">
    <div class="container">
    <div class="navbar-header">
      <a href="#" class="navbar-brand">Pretty Blog</a>
    </div>
      <ul class="nav navbar-nav navbar-right">
        <li><a href ng-click="post()" ng-show="$root.loggedIn">New</a></li>
        <li><a href ng-click="menu()">Menu</a></li>
      </ul>
    </div>
  </nav>

  <!-- User Menu -->
  <div class='overlay-dropdown' ng-show="$root.menuOpen">

    <span class='glyphicon glyphicon-remove' ng-click="close()"></span>
    <div class="spacer"></div>

    <ul class="menu-options">
      <li><a href ng-click="logOut()" ng-show="$root.loggedIn">Sign Out</a>
      </li>
      <li><a href ng-click="editAccount()" ng-show="$root.loggedIn && !$root.account">Edit Account</a>
      </li>
    </ul>

    <!-- User Log In Form -->
    <login-form></login-form>

    <!-- Edit Account Form -->
    <edit-account></edit-account>

  </div>

  <!-- New Post Form -->
  <div class='overlay-dropdown' ng-show="$root.newPost">

    <span class='glyphicon glyphicon-remove' ng-click="close()"></span>
    <div class="spacer"></div>

    <!-- New Post Form -->
    <post-form></post-form>
  </div>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html ng-app="blog">
<head>
  <title>Pretty Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>